### ISSUE TITLE
1.6.4 not found

### ISSUE THREAD

**Issue by StanGirard** [Luxoft/cordentity#39]
I'm currently running it on ubuntu 18.04.
JDK installed, graddle installed, libindy installed.

It cannot find the version 1.6.4 on everdym.
I tried changing it to other versions, 1.8.1 per example but still not working.

```
* What went wrong:
Could not resolve all files for configuration ':indy-utils:compileClasspath'.
> Could not resolve org.hyperledger:indy:1.6.4.
  Required by:
      project :indy-utils
   > Could not resolve org.hyperledger:indy:1.6.4.
      > Could not get resource 'https://repo.evernym.com/artifactory/libindy-maven-local/org/hyperledger/indy/1.6.4/indy-1.6.4.pom'.
         > Could not GET 'https://repo.evernym.com/artifactory/libindy-maven-local/org/hyperledger/indy/1.6.4/indy-1.6.4.pom'.
            > Connect to repo.evernym.com:443 [repo.evernym.com/35.166.202.228] failed: Connection timed out (Connection timed out)
```

**Comment by seniorjoinu** [comment]
As the error says: "Connection timed out". 
It could mean only 2 things: 
1. There is something wrong with your connection.
2. There is something wrong with evernym's connection.

I'm also unable to reach repo.evernym.com, so the problem seems to be on their side.

**Comment by noah4477** [comment]
It has been migrated to https://repo.sovrin.org/repository/maven-releases

**Comment by pranavkirtani88** [comment]
is this resolved? I am facing the same issue

**Comment by seniorjoinu** [comment]
Yes, come here - https://github.com/hyperledger-labs/cordentity

**Comment by alkopnin** [comment]
@pranavkirtani88 
This repo will be closed soon, we do not maintain it because already migrated to Hyperledger lab.
